services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: forum-app
    volumes:
      - ./:/app
      - ./docker/Caddyfile:/etc/frankenphp/Caddyfile
      - ./docker/logs:/var/log/caddy
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "443:443/udp"# HTTP/3
    restart: no
    env_file:
      - .env
    depends_on:
      - db
    tty: true
  db:
    image: mysql:8.0
    container_name: forum-mysql
    restart: no
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  mysql_data: